### ISSUE TITLE
SHA256 are invalid key identifiers for Droplet creation

### ISSUE THREAD

**Issue by zzq889** [hermanjunge/k8s-do-tf#10]
I ran the latest code under osx and it is still need to use below scripts to generate signature

```
export TF_VAR_ssh_fingerprint=$(ssh-keygen -E MD5 -lf ~/.ssh/id_rsa.pub | awk '{print $2}' | sed 's/MD5://g')
```

Or I'll get output like: 

```
Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 SHA256:<key> are invalid key identifiers for Droplet creation.
```

**Comment by 5tefan** [comment]
Can you paste the output of `ssh -version` on your machine?

I'm on osx and the other command was working for me so I took out the ["if Darwin" statement](https://github.com/hermanjunge/kubernetes-digitalocean-terraform/blob/48ff711e6c26ba3e5ce604afe5351f0deb8e5084/hack/setup_terraform.sh#L10). But it looks like we still need it, possibly conditioning on `ssh -version` since `uname` doesn't seem to sufficiently determine the command we need.

**Comment by zzq889** [comment]
I use 10.12 default ssh client which is `OpenSSH_7.2p2` and `LibreSSL 2.4.1`

**Comment by 5tefan** [comment]
Eek, my OpenSSH was a bit out of date. 

I can't find any mention of the -E option before [OpenSSH_6.9](http://www.openssh.com/releasenotes.html). Confirmed we need the `-E` version on CoreOS stable with OpenSSH version 7.2. Debian Jessie appears to be on OpenSSH 6.7 and does not take the `-E` option. 

Hopefully 6.9 is the correct cutoff. I've put a switch based on OpenSSH version into the setup script and opened PR #11. I'll merge it soon unless you have more comments.

Thanks for pointing this out :)
