### ISSUE TITLE
`BASH_REMATCH` doesn't work well with `zsh`

### ISSUE THREAD

**Issue by alpe** [hermanjunge/k8s-do-tf#14]
See: https://github.com/hermanjunge/kubernetes-digitalocean-terraform/blob/master/setup_terraform.sh#L10

The previous condition worked better for me. I'm on OSX

**Comment by 5tefan** [comment]
This is similar to #10... TL;DR: Needing the `ssh-keygen -E` variant depends on OpenSSH version >= 6.9, not necessarily on OS. 

I don't think we should revert to the [if [[ `uname` == 'Darwin' ]]](https://github.com/hermanjunge/kubernetes-digitalocean-terraform/blob/8b364917cac1e84c14d0f03f847f52c12888284f/setup_terraform.sh) version since presumably Linux distros will eventually be using V6.9+ and this will be an issue again. 

A potential solution might be to use this [reMatch function](http://stackoverflow.com/a/22539067/2177568):

```
# SYNOPSIS
#   reMatch string regex
# DESCRIPTION
#   Multi-shell implementation of the =~ regex-matching operator;
#   works in: bash, ksh, zsh
#
#   Matches STRING against REGEX and returns exit code 0 if they match.
#   Additionally, the matched string(s) is returned in array variable ${reMatch[@]},
#   which works the same as bash's ${BASH_REMATCH[@]} variable: the overall
#   match is stored in the 1st element of ${reMatch[@]}, with matches for
#   capture groups (parenthesized subexpressions), if any, stored in the remaining
#   array elements.
#   NOTE: zsh arrays by default start with index *1*.
# EXAMPLE:
#   reMatch 'This AND that.' '^(.+) AND (.+)\.' # -> ${reMatch[@]} == ('This AND that.', 'This', 'that')
function reMatch {
  typeset ec
  unset -v reMatch # initialize output variable
  [[ $1 =~ $2 ]] # perform the regex test
  ec=$? # save exit code
  if [[ $ec -eq 0 ]]; then # copy result to output variable
    [[ -n $BASH_VERSION ]] && reMatch=( "${BASH_REMATCH[@]}" )
    [[ -n $KSH_VERSION ]]  && reMatch=( "${.sh.match[@]}" )
    [[ -n $ZSH_VERSION ]]  && reMatch=( "$MATCH" "${match[@]}" )
  fi
  return $ec
}
```

I haven't tested this, but this seems to be getting pretty crazy for the "convenience script".

**Comment by 5tefan** [comment]
@hermanjunge I have no experience supporting cross shell scripting. Do you have any preference on this? Easiest solution for us might be to add "Bash shell" to the requirements in the readme.

**Comment by alpe** [comment]
alternatively you could check for empty string in `version` and use `-E MD5` as default

**Comment by ghost** [comment]
@5tefan `if [[ uname == 'Darwin' ]]` is the path with less headaches. Unless we want to fix the requirements. Your call.
