### ISSUE TITLE
Question: How do you decide on which version of hyperkube to use?

### ISSUE THREAD

**Issue by aknuds1** [hermanjunge/k8s-do-tf#34]
I see that you're defaulting to version 1.5.4_coreos.0 of hyperkube, how do you decide? The latest one is 1.6.2 as far as I can tell. Is it safe to bump the default version to this?

**Comment by 5tefan** [comment]
In general, the configuration here implements the instructions from the CoreOS Kubernetes guide [1]. Only bumping the version may work, but not always.... as turned out to be the problem causing #27. Also, I learned the hard way (pr #28, issue #30, pr #31) that "blindly" implementing the CoreOS guide may not completely work (anymore?)... so 1.5.4 is the current manually tested, working version.

Having some testing would make it more possible to keep up to speed with the latest k8s version and prevent errors, but thats a wishlist item :) 

[1] https://coreos.com/kubernetes/docs/1.5.4/getting-started.html

**Comment by 5tefan** [comment]
As an aside about testing, I... and seems probably some others use this as a template in our own clusters, so the configuration here does see real usage. ...Meaning probably any issues from upgrading will be noticed, but that's also dependent on motivation to port updates and speaking from experience... once you get a reliable cluster up and running, it's nice to just leave it alone.

**Comment by ghost** [comment]
> once you get a reliable cluster up and running, it's nice to just leave it alone

And that one, is the lesson we all learn *the hard way* 😄 

Write the scripts, deploy it. It works? No way... Let's stress it a little bit more. It's still working? Good. Leave it alone!
